on:
  pull_request:
  push:
  schedule:
    - cron: '16 20 * * 6'

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Test Action
        uses: ./
        with:
          args: '-h'
  build-push:
    uses: reitermarkus/.github/.github/workflows/docker-build-push.yml@main
