on:
  pull_request:
  push:
  schedule:
    - cron: '16 20 * * 6'

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Test Action
        uses: ./
        with:
          args: '-h'
  build-push:
    uses: reitermarkus/.github/.github/workflows/docker-build-push.yml@main
