on:
  pull_request:
  push:
  schedule:
    - cron: '16 20 * * 6'

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - name: Test Action
        uses: ./
        with:
          args: '-h'
  build-push:
    uses: reitermarkus/.github/.github/workflows/docker-build-push.yml@main
